/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_brewchain_evfs_jni_Merklezksnark_TestFullCase */

#ifndef _Included_org_brewchain_evfs_jni_Merklezksnark_TestFullCase
#define _Included_org_brewchain_evfs_jni_Merklezksnark_TestFullCase
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
